<?php
/**
 * Created by PhpStorm.
 * User: gsj
 * Date: 2020/7/27
 * Time: 14:02
 */

namespace App\Admin\Metrics\Device_content;

use Dcat\Admin\Widgets\Metrics\Round;
use Illuminate\Http\Request;
use App\Admin\Model\DeviceLog;
use App\Admin\Model\DeviceVideo;

class DeviceVideoContent extends Round
{
    private $id;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->title('设备视频');
    }

    public function handle(Request $request)
    {
        $id = '1';
        $log = DeviceVideo::where('device_id', $id)->first();
        $this->device_content($log->name, $log->id, $log->created_at, $log->updated_at);
    }

    public function device_content($name,$id,$created_at,$updated_at)
    {
        return $this->content(
            <<<HTML
<div>
<div>
ID:{$id}
</div>
<div>
名字：{$name}
</div>
<div>
创建时间：{$created_at}
</div>
<div>
更新时间：{$updated_at}
</div>
</div>
HTML
        );

    }
}